"""Built-in PFP theme library.

The bot never repeats a theme that has been recorded in the used-theme history.
Admins can also add custom themes from Discord with /pfp theme-add.
"""

THEME_CATEGORIES = {
    "Movies & TV": [
        "Star Wars", "Harry Potter", "Lord of the Rings", "The Hobbit", "Game of Thrones",
        "House of the Dragon", "Stranger Things", "Wednesday", "Bridgerton", "Peaky Blinders",
        "The Walking Dead", "Breaking Bad", "Better Call Saul", "The Office", "Friends",
        "Brooklyn Nine-Nine", "The Boys", "Fallout", "The Last of Us", "Arcane",
        "Squid Game", "Money Heist", "Black Mirror", "Doctor Who", "Sherlock",
        "Supernatural", "Lucifer", "Vikings", "The Witcher", "Cobra Kai",
        "Pirates of the Caribbean", "Jurassic Park", "Ghostbusters", "Men in Black", "The Matrix",
        "Back to the Future", "Indiana Jones", "Mission Impossible", "James Bond", "Top Gun",
        "Rocky", "Rambo", "John Wick", "Mad Max", "Blade Runner",
        "Dune", "Avatar", "Planet of the Apes", "Transformers", "Godzilla",
        "King Kong", "Jaws", "Alien", "Predator", "Terminator",
        "The Hunger Games", "Twilight", "The Addams Family", "Beetlejuice", "Edward Scissorhands",
        "Charlie and the Chocolate Factory", "Alice in Wonderland", "The Wizard of Oz", "Narnia", "Peter Pan",
        "Mary Poppins", "Barbie", "Mean Girls", "Clueless", "Legally Blonde",
        "Grease", "Mamma Mia", "Dirty Dancing", "The Great Gatsby", "Breakfast at Tiffany's",
        "Pulp Fiction", "Kill Bill", "Fight Club", "Scarface", "The Godfather",
        "Goodfellas", "Ocean's Eleven", "Knives Out", "Glass Onion", "The Grand Budapest Hotel",
        "Studio Ghibli", "Spirited Away", "Howl's Moving Castle", "Princess Mononoke", "My Neighbor Totoro",
        "Coraline", "The Nightmare Before Christmas", "Corpse Bride", "ParaNorman", "Kubo and the Two Strings",
        "Shrek", "Kung Fu Panda", "How to Train Your Dragon", "Madagascar", "Ice Age",
        "Despicable Me", "Minions", "Megamind", "The Incredibles", "Ratatouille",
        "Cars", "Monsters Inc", "Finding Nemo", "Toy Story", "Inside Out",
        "Coco", "Encanto", "Frozen", "Moana", "Tangled",
        "Mulan", "Aladdin", "The Lion King", "Beauty and the Beast", "The Little Mermaid",
        "Lilo & Stitch", "Wreck-It Ralph", "Big Hero 6", "Zootopia", "Turning Red",
    ],
    "Comics & Heroes": [
        "Marvel Heroes", "Marvel Villains", "DC Heroes", "DC Villains", "Spider-Verse",
        "Batman Villains", "Gotham Characters", "X-Men", "Avengers", "Guardians of the Galaxy",
        "Fantastic Four", "Deadpool", "Venom", "Suicide Squad", "Justice League",
        "Teen Titans", "Watchmen", "The Umbrella Academy", "Invincible", "Comic Book Antiheroes",
        "Supervillains", "Sidekicks", "Secret Identities", "Masked Vigilantes", "Retro Superheroes",
        "Golden Age Comics", "Comic Book Scientists", "Comic Book Royalty", "Comic Book Monsters", "Comic Book Aliens",
        "Superheroes Gone Wrong", "Villains on Vacation", "Heroes in Pajamas", "Superhero Pets", "Fake Superheroes",
    ],
    "Games": [
        "Pokémon", "Pokémon Villains", "Pokémon Gym Leaders", "Legendary Pokémon", "Cute Pokémon",
        "Mario", "Mario Villains", "The Legend of Zelda", "Animal Crossing", "Kirby",
        "Sonic the Hedgehog", "Minecraft", "Fortnite", "Overwatch", "Valorant",
        "League of Legends", "World of Warcraft", "Diablo", "Hearthstone", "Final Fantasy",
        "Kingdom Hearts", "Elden Ring", "Dark Souls", "Bloodborne", "Sekiro",
        "Skyrim", "Fallout Games", "Cyberpunk 2077", "The Witcher Games", "Baldur's Gate",
        "Mass Effect", "Dragon Age", "Assassin's Creed", "Far Cry", "Watch Dogs",
        "Grand Theft Auto", "Red Dead Redemption", "The Sims", "Stardew Valley", "Terraria",
        "Roblox", "Among Us", "Fall Guys", "Rocket League", "Apex Legends",
        "Call of Duty", "Battlefield", "Halo", "Destiny", "Warframe",
        "Resident Evil", "Silent Hill", "Five Nights at Freddy's", "Dead by Daylight", "Outlast",
        "Little Nightmares", "Bendy and the Ink Machine", "Poppy Playtime", "Doki Doki Literature Club", "Undertale",
        "Deltarune", "Hades", "Hollow Knight", "Cuphead", "Celeste",
        "Ori", "Dead Cells", "Cult of the Lamb", "Dave the Diver", "Untitled Goose Game",
        "Portal", "Half-Life", "Team Fortress 2", "Left 4 Dead", "Counter-Strike",
        "Street Fighter", "Tekken", "Mortal Kombat", "Soulcalibur", "Super Smash Bros",
        "Genshin Impact", "Honkai Star Rail", "Zenless Zone Zero", "Persona", "Fire Emblem",
        "Metal Gear", "Death Stranding", "Tomb Raider", "Uncharted", "God of War",
        "BioShock", "Borderlands", "DOOM", "Quake", "Retro Arcade Games",
    ],
    "Animation & Cartoons": [
        "The Simpsons", "Futurama", "Family Guy", "South Park", "Rick and Morty",
        "Adventure Time", "Regular Show", "Gravity Falls", "Steven Universe", "The Amazing World of Gumball",
        "SpongeBob SquarePants", "Avatar: The Last Airbender", "The Legend of Korra", "Teenage Mutant Ninja Turtles", "Scooby-Doo",
        "Looney Tunes", "Tom and Jerry", "The Flintstones", "The Jetsons", "Popeye",
        "Powerpuff Girls", "Dexter's Laboratory", "Johnny Bravo", "Courage the Cowardly Dog", "Ed, Edd n Eddy",
        "Kim Possible", "Phineas and Ferb", "DuckTales", "Chip 'n Dale", "Darkwing Duck",
        "Garfield", "Peanuts", "Calvin and Hobbes", "Care Bears", "My Little Pony",
        "Hello Kitty", "Sanrio Characters", "Moomins", "Smurfs", "Trolls",
        "Winx Club", "Monster High", "Bratz", "Totally Spies", "Miraculous Ladybug",
        "Anime Heroes", "Anime Villains", "Anime Side Characters", "Anime Teachers", "Anime Monsters",
        "Dragon Ball", "Naruto", "One Piece", "Demon Slayer", "Jujutsu Kaisen",
        "Attack on Titan", "My Hero Academia", "Sailor Moon", "Death Note", "Fullmetal Alchemist",
        "Hunter x Hunter", "Bleach", "JoJo's Bizarre Adventure", "Chainsaw Man", "Spy x Family",
    ],
    "Fantasy & Mythology": [
        "Greek Gods", "Greek Goddesses", "Greek Monsters", "Norse Gods", "Norse Mythology",
        "Egyptian Gods", "Celtic Mythology", "Roman Gods", "Japanese Mythology", "Chinese Mythology",
        "Slavic Mythology", "Arthurian Legends", "Knights of the Round Table", "Medieval Royalty", "Medieval Knights",
        "Wizards", "Witches", "Warlocks", "Sorcerers", "Alchemists",
        "Necromancers", "Paladins", "Rogues", "Bards", "Druids",
        "Elves", "Dark Elves", "Fairies", "Pixies", "Goblins",
        "Orcs", "Trolls", "Dwarves", "Giants", "Mermaids",
        "Sirens", "Vampires", "Werewolves", "Ghosts", "Demons",
        "Angels", "Fallen Angels", "Dragons", "Phoenixes", "Griffins",
        "Unicorns", "Pegasus", "Centaurs", "Minotaurs", "Gargoyles",
        "Forest Spirits", "Sea Monsters", "Cryptids", "Urban Legends", "Fairy Tale Villains",
        "Fairy Tale Heroes", "Cursed Royalty", "Enchanted Forest", "Haunted Castle", "Magic Academy",
        "Fantasy Tavern", "Potion Makers", "Treasure Hunters", "Monster Hunters", "Dragon Riders",
        "Pirates", "Vikings", "Samurai", "Ninjas", "Spartans",
        "Gladiators", "Musketeers", "Outlaws", "Bounty Hunters", "Assassins",
    ],
    "Horror & Spooky": [
        "Classic Horror Monsters", "Slasher Villains", "Horror Movie Survivors", "Haunted Dolls", "Possessed Toys",
        "Creepy Clowns", "Haunted Houses", "Ghost Hunters", "Paranormal Investigators", "Urban Legend Creatures",
        "Zombies", "Skeletons", "Mummies", "Scarecrows", "Grim Reapers",
        "Cursed Paintings", "Cursed Objects", "Abandoned Carnival", "Haunted Circus", "Gothic Horror",
        "Victorian Ghosts", "Vampire Aristocracy", "Werewolf Pack", "Zombie Prom", "Monster Prom",
        "Cute Horror", "Pastel Horror", "Retro Horror Posters", "B-Movie Monsters", "Creature Feature",
        "Found Footage Horror", "Campfire Legends", "Nightmare Creatures", "Sleep Paralysis Demons", "Backrooms Creatures",
        "Analog Horror", "Creepy Mascots", "Evil Puppets", "Haunted Masks", "Monster Under the Bed",
        "Final Girls", "Horror Nurses", "Mad Scientists", "Lab Experiments", "Apocalypse Survivors",
        "Post-Apocalypse Raiders", "Radioactive Mutants", "Alien Abductions", "Area 51", "Zombie Office Workers",
    ],
    "Animals": [
        "Cats", "Black Cats", "Orange Cats", "Cats in Suits", "Cats as Royalty",
        "Dogs", "Tiny Dogs", "Big Dogs", "Dogs in Sunglasses", "Dogs as Detectives",
        "Sharks", "Cute Sharks", "Business Sharks", "Sharks on Vacation", "Sharks in Space",
        "Frogs", "Fancy Frogs", "Wizard Frogs", "Cowboy Frogs", "Frogs with Jobs",
        "Ducks", "Chaotic Ducks", "Ducks on Skateboards", "Royal Ducks", "Detective Ducks",
        "Raccoons", "Trash Pandas", "Raccoons with Jobs", "Raccoon Mafia", "Raccoons in Space",
        "Capybaras", "Capybaras on Vacation", "Capybara Royalty", "Capybara Mafia", "Capybara Office Workers",
        "Red Pandas", "Pandas", "Koalas", "Sloths", "Otters",
        "Penguins", "Polar Bears", "Brown Bears", "Foxes", "Arctic Foxes",
        "Wolves", "Coyotes", "Hyenas", "Lions", "Tigers",
        "Leopards", "Cheetahs", "Panthers", "Lynxes", "Bobcats",
        "Elephants", "Rhinos", "Hippos", "Giraffes", "Zebras",
        "Gorillas", "Chimpanzees", "Orangutans", "Lemurs", "Meerkats",
        "Hedgehogs", "Hamsters", "Guinea Pigs", "Rabbits", "Mice",
        "Bats", "Owls", "Crows", "Ravens", "Parrots",
        "Flamingos", "Peacocks", "Pigeons", "Chickens", "Geese",
        "Axolotls", "Octopuses", "Jellyfish", "Seahorses", "Whales",
        "Dolphins", "Orcas", "Manta Rays", "Crabs", "Lobsters",
        "Snakes", "Geckos", "Chameleons", "Turtles", "Crocodiles",
        "Dinosaurs", "T-Rexes", "Velociraptors", "Triceratops", "Pterodactyls",
    ],
    "Aesthetics": [
        "Dark Academia", "Light Academia", "Cottagecore", "Goblincore", "Fairycore",
        "Mermaidcore", "Angelcore", "Devilcore", "Royalcore", "Knightcore",
        "Piratecore", "Witchcore", "Vampirecore", "Clowncore", "Kidcore",
        "Dreamcore", "Weirdcore", "Traumacore", "Cybercore", "Webcore",
        "Y2K", "Cyber Y2K", "McBling", "Indie Sleaze", "Tumblr 2014",
        "Grunge", "Soft Grunge", "Punk", "Goth", "Pastel Goth",
        "Romantic Goth", "Victorian Goth", "Mall Goth", "Emo", "Scene",
        "Kawaii", "Pastel", "Coquette", "Balletcore", "Barbiecore",
        "Dollcore", "Princesscore", "Regencycore", "Victorian", "Edwardian",
        "Art Deco", "Art Nouveau", "Bauhaus", "Brutalism", "Minimalism",
        "Maximalism", "Retro Futurism", "Atompunk", "Steampunk", "Dieselpunk",
        "Cyberpunk", "Solarpunk", "Biopunk", "Clockpunk", "Cassette Futurism",
        "Vaporwave", "Synthwave", "Retrowave", "Mallsoft", "Frutiger Aero",
        "Liminal Spaces", "Neon Noir", "Film Noir", "Old Hollywood", "Hollywood Glamour",
        "Disco", "Glam Rock", "Rockabilly", "Pin-Up", "Hippie",
        "Bohemian", "Western", "Space Cowboy", "Desert Punk", "Apocalyptic Chic",
        "Luxury", "Quiet Luxury", "Old Money", "Mob Wife", "Mafia Glam",
        "Office Siren", "Corporate Chic", "Techwear", "Streetwear", "Harajuku",
        "Decora", "Lolita Fashion", "Visual Kei", "K-Pop Idol", "J-Rock",
        "Monochrome", "Black and White", "Neon", "Holographic", "Iridescent",
    ],
    "Eras & History": [
        "Ancient Egypt", "Ancient Greece", "Ancient Rome", "Stone Age", "Bronze Age",
        "Iron Age", "Medieval Europe", "Renaissance", "Baroque", "Rococo",
        "Regency Era", "Victorian Era", "Edwardian Era", "Wild West", "Gilded Age",
        "Roaring Twenties", "1930s Noir", "1940s", "1950s", "1960s",
        "1970s", "1980s", "1990s", "2000s", "2010s",
        "Viking Age", "Feudal Japan", "Ancient China", "Aztec Empire", "Maya Civilization",
        "Inca Empire", "Golden Age of Piracy", "Age of Exploration", "Belle Époque", "Prohibition Era",
        "Jazz Age", "Disco Era", "Space Age", "Cold War Spy Style", "Retro NASA",
        "Victorian Inventors", "Medieval Peasants", "Renaissance Artists", "Royal Court", "Wild West Outlaws",
        "Wild West Sheriffs", "1920s Gangsters", "1940s Detectives", "1950s Diners", "1960s Mod",
        "1970s Disco", "1980s Aerobics", "1980s Action Heroes", "1990s Sitcom", "2000s Pop Stars",
    ],
    "Jobs & Archetypes": [
        "Detectives", "Private Investigators", "Spies", "Secret Agents", "Bodyguards",
        "Police Detectives", "Firefighters", "Paramedics", "Doctors", "Nurses",
        "Surgeons", "Scientists", "Mad Scientists", "Astronauts", "Engineers",
        "Mechanics", "Pilots", "Flight Attendants", "Sailors", "Captains",
        "Chefs", "Bakers", "Bartenders", "Baristas", "Waiters",
        "Librarians", "Teachers", "Professors", "Students", "Principals",
        "Lawyers", "Judges", "Journalists", "Photographers", "Reporters",
        "Artists", "Painters", "Sculptors", "Writers", "Poets",
        "Rock Stars", "Pop Stars", "DJs", "Rappers", "Opera Singers",
        "Actors", "Directors", "Stunt Performers", "Circus Performers", "Magicians",
        "Fortune Tellers", "Tarot Readers", "Astrologers", "Ghost Hunters", "Treasure Hunters",
        "Cowboys", "Cowgirls", "Sheriffs", "Bandits", "Bikers",
        "Mafia Bosses", "Gangsters", "Casino Dealers", "High Rollers", "Heist Crew",
        "Royal Guards", "Queens", "Kings", "Princes", "Princesses",
        "Butlers", "Maids", "Gardeners", "Farmers", "Fishermen",
        "Office Workers", "CEOs", "Interns", "Accountants", "IT Support",
        "Influencers", "Streamers", "Gamers", "Hackers", "Robots",
    ],
    "Chaos & Comedy": [
        "Bad Passport Photos", "Fake Mugshots", "Awkward Family Photos", "School Picture Day", "Terrible Yearbook Photos",
        "Mid-Sneeze", "Caught Off Guard", "Monday Morning Faces", "No Sleep Club", "After One Coffee",
        "Before Coffee", "Overcaffeinated", "Lost Tourists", "Confused Detectives", "Failed Superheroes",
        "Budget Supervillains", "Discount Royalty", "Knockoff Wizards", "Suspicious Grandparents", "Chaotic Grandmas",
        "Chaotic Grandpas", "Angry Toddlers", "Tiny Businesspeople", "Animals with Human Jobs", "Pets in Suits",
        "Pets with Sunglasses", "Animals at the Office", "Animals in Therapy", "Animals on Vacation", "Animals in Space",
        "Food with Faces", "Objects with Faces", "Cursed Stock Photos", "Cursed Renaissance Paintings", "Cursed Medieval Art",
        "Badly Drawn Royalty", "Dramatic Renaissance Portraits", "Overly Serious Pets", "Tiny Hats", "Huge Sunglasses",
        "Matching Mustaches", "Terrible Haircuts", "Unnecessary Eyepatches", "Fake Mustaches", "Ridiculous Wigs",
        "Conspiracy Theorists", "Alien Witnesses", "Area 51 Employees", "Time Travelers", "People from the Future",
        "People from the Wrong Century", "NPC Energy", "Main Character Syndrome", "Side Quest Characters", "Final Boss Energy",
        "Background Characters", "Villains with Day Jobs", "Heroes on Their Day Off", "Monsters at Work", "Wizards with Office Jobs",
        "Pirates with Office Jobs", "Vikings at the Supermarket", "Knights at the Mall", "Cowboys in Space", "Astronauts at the Beach",
        "Royalty at McDonald's", "Medieval Influencers", "Victorian Influencers", "Zombie Influencers", "Vampire Influencers",
        "Grandma Core", "Dad on Vacation", "Mom at the Airport", "Uncle at a Barbecue", "Family WhatsApp Profile Photos",
        "Facebook Mom Photos", "LinkedIn Gone Wrong", "Corporate Headshots Gone Wrong", "Passport Photo Chaos", "Low-Budget Movie Posters",
        "Reality TV Contestants", "Fake Politicians", "Fake Millionaires", "Fake Celebrities", "Fake Detectives",
        "Wanted Posters", "Missing Person Posters", "Retro Ads Gone Wrong", "Infomercial Hosts", "Soap Opera Drama",
        "Dramatic Side-Eye", "People Who Know a Secret", "Suspicious Neighbors", "Nosy Neighbors", "HOA Villains",
        "Airport Characters", "People at 3 AM", "People After a 12-Hour Shift", "People Who Missed the Bus", "People Who Lost Their Keys",
        "People Pretending Everything Is Fine", "Delulu Era", "Professional Overthinkers", "Chaos Coordinators", "Certified Menaces",
        "Tiny Villains", "Polite Villains", "Villains in Therapy", "Villains at Brunch", "Villains on Vacation",
    ],
    "Food & Objects": [
        "Pizza", "Sushi", "Tacos", "Burgers", "French Fries",
        "Donuts", "Cupcakes", "Ice Cream", "Candy", "Chocolate",
        "Cookies", "Croissants", "Pancakes", "Waffles", "Cereal Mascots",
        "Coffee", "Bubble Tea", "Milkshakes", "Smoothies", "Energy Drinks",
        "Fruit", "Strawberries", "Cherries", "Watermelons", "Lemons",
        "Mushrooms", "Hot Peppers", "Avocados", "Potatoes", "Tomatoes",
        "Rubber Ducks", "Lava Lamps", "Vintage Cameras", "Cassette Tapes", "Vinyl Records",
        "Old Televisions", "Retro Computers", "Flip Phones", "Arcade Machines", "Polaroids",
        "Tarot Cards", "Playing Cards", "Chess Pieces", "Dice", "Crystal Balls",
        "Keys", "Clocks", "Mirrors", "Candles", "Lanterns",
        "Teacups", "Perfume Bottles", "Jewelry Boxes", "Music Boxes", "Snow Globes",
        "Plush Toys", "Action Figures", "Porcelain Dolls", "Teddy Bears", "Toy Robots",
        "Traffic Cones", "Shopping Carts", "Vending Machines", "Gumball Machines", "Neon Signs",
    ],
    "Nature & Space": [
        "Sun", "Moon", "Stars", "Planets", "Constellations",
        "Zodiac Signs", "Solar System", "Astronaut Portraits", "Aliens", "Friendly Aliens",
        "Retro Aliens", "Space Pirates", "Space Royalty", "Space Explorers", "Galaxy",
        "Nebula", "Black Holes", "Comets", "Meteor Showers", "Aurora",
        "Clouds", "Storms", "Lightning", "Rain", "Snow",
        "Tornadoes", "Volcanoes", "Deserts", "Jungles", "Rainforests",
        "Enchanted Forests", "Mushroom Forests", "Underwater World", "Coral Reef", "Deep Sea",
        "Mountains", "Waterfalls", "Wildflowers", "Sunflowers", "Roses",
        "Cherry Blossoms", "Autumn Leaves", "Cacti", "Succulents", "Bioluminescence",
        "Four Seasons", "Sunset", "Sunrise", "Eclipse", "Northern Lights",
    ],
    "Seasonal & Events": [
        "Halloween", "Cute Halloween", "Vintage Halloween", "Christmas", "Ugly Christmas Sweaters",
        "Christmas Villains", "Santa's Workshop", "Gingerbread People", "Winter Wonderland", "New Year's Eve",
        "Valentine's Day", "Anti-Valentine", "Cupid", "Spring", "Summer",
        "Autumn", "Winter", "Beach Day", "Pool Party", "Summer Camp",
        "Camping Trip", "Road Trip", "Festival Season", "Carnival", "Circus",
        "Masquerade Ball", "Prom Night", "Homecoming", "Graduation", "Birthday Party",
        "Tea Party", "Garden Party", "Sleepover", "Pajama Party", "Costume Party",
        "Murder Mystery Party", "Casino Night", "Disco Night", "Karaoke Night", "Movie Night",
        "Game Night", "Sports Day", "School Day", "Office Party", "Wedding Guests",
        "Royal Wedding", "Apocalypse Party", "Zombie Party", "Vampire Ball", "Witch Coven",
    ],
    "Music & Pop Culture": [
        "Rock Bands", "Metal Bands", "Punk Bands", "Pop Stars", "Boy Bands",
        "Girl Groups", "K-Pop Idols", "Disco Stars", "Glam Rock Stars", "Emo Bands",
        "Festival Looks", "Album Covers", "Retro Album Covers", "Fake Album Covers", "One-Hit Wonders",
        "Music Video Characters", "80s Music Videos", "90s Music Videos", "2000s Music Videos", "Eurovision",
        "Broadway Musicals", "Movie Musicals", "Opera Characters", "Ballet Characters", "Circus Music",
        "Rockabilly", "Heavy Metal", "Goth Rock", "Pop Punk", "Synthpop",
        "Country Music", "Jazz Musicians", "Blues Musicians", "Classical Composers", "Orchestra Members",
        "DJs", "Ravers", "Festival Headliners", "Backstage Crew", "Roadies",
    ],
}

# Flatten and deduplicate while preserving category order.
THEMES = []
_seen = set()
for _category, _items in THEME_CATEGORIES.items():
    for _theme in _items:
        _key = _theme.casefold().strip()
        if _key not in _seen:
            _seen.add(_key)
            THEMES.append(_theme)

THEME_COUNT = len(THEMES)
